services:
  db:
    image: postgres:16
    container_name: yourapp-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yourapp
    ports:
      - "5432:5432"
    volumes:
      - yourapp_pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: yourapp-backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - backend/.env
    environment:
      # Ensure DB host resolves inside the network
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/yourapp?sslmode=disable}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN:-http://localhost:3000}
      PORT: ${PORT:-8080}
    ports:
      - "8080:8080"

volumes:
  yourapp_pg_data: